### ISSUE TITLE
site review 2

### ISSUE THREAD

**Issue by chrswng** [GovLab/data-collaboratives#121]
index
- [x] edit subtitle to CREATING PUBLIC VALUE BY EXCHANGING DATA
- [x] anything we can do to make the video header start playing at a smaller screen width? [low priority] 
- [x] add white border to "LEARN MORE ABOUT DATA COLLABORATIVES" button and use yellow as hover color
- [x] MORE button in Data Responsibility Framework (in quadrant) should go to http://datacollaboratives.org/framework.html
- [x] under SECTIONS footer, change "WHAT IS DATA COLLABORATIVES" to "WHAT ARE DATA COLLABORATIVES"
- [x] under PARTNERS footer (after Tandon logo), add "COLLABORATE WITH US" button with mailto:andrew@thegovlab.org

resources
- [x] modify modal so it's not under the top nav overlay
<img width="1350" alt="screen shot 2017-01-15 at 1 58 36 pm" src="https://cloud.githubusercontent.com/assets/8985721/21965344/1dd08484-db2c-11e6-9a32-d1466b7ee02d.png">

team
- [x] add mark (in between denny and claudio)
- [x] add greyson and robert (after prianka) to project support section
use the short bios and pics from here http://www.thegovlab.org/team.html

ADD ANALYTICS (use UA-40012093-10)

**Comment by claudioccm** [comment]
- Just fixed the top-nav / modal issue. I introduced that on my previous push. 
- The video doesn't work on mobiles intentionally. Usually mobile users are using data plans, and in many places, that is still charged by MB. So I don't think we should download a 3MB video just for fun. Hehe.

**Comment by chrswng** [comment]
Yeah not saying for mobile, def with you there, but there's a lot of real estate between where it is now and mobile. If it can be improved great, but again, low priority

**Comment by claudioccm** [comment]
I think it should work all the way down to tablets. But stay static in phones.

**Comment by mocxd** [comment]
video is set to work down to 1200px for now (just put a div behind it at -2 z-index to fix that white bar issue) so it will play better with browsers that arent 100% expanded on 1280 screens (mine was 1279), but probably need to take a closer look at css  and/or maybe get a video that has a different aspect ratio to go to smaller screens (like down to 600px)
