### ISSUE TITLE
case.scss !important stravaganza

### ISSUE THREAD

**Issue by claudioccm** [GovLab/data-collaboratives#35]
Understanding "CSS Specificity" will help you avoid the "!important" proliferation.
https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/

Let me know if you need help on this. This is indeed one of the most complicated topics in css.

**Comment by enabek** [comment]
- You should always try to use IDs to increase the specificity.
- A class selector beats any number of element selectors
- Never use !important :'(
