### ISSUE TITLE
html / markdownify (small) problem

### ISSUE THREAD

**Issue by claudioccm** [GovLab/data-collaboratives#46]
`/canvas/phase-1-demand.html`

`{{ phaseStep.stepTitle | markdownify }}` is generating this:

```
<h4>
  <p><strong>Step 1:</strong> Define the problem to be solved</p>
</h4>
```

I get that it is advisable to pull the `strong` from the markdown, but ideally we would pull it as an `h4` directly, and not adding a `p` inside the `h4`. This is essentially wrong.

Unless we are doing this as a future proof thing, to have multiple phases/steps, I think abstracting this in markdown is overkill. @chrswng, any thoughts on this?

**Comment by chrswng** [comment]
@claudioccm is this complaint about the specific `step title` line or the entire strategy of markdown for the steps? if it's just the `step title` issue specifically i'm fine with making that line `h4`
